compile:
	g++ *.cpp vendors/stb_image/*.cpp vendors/imgui/*.cpp -lglfw -lGLEW -framework OpenGL -std=c++11

debug:
	g++ -g Application.cpp -lglfw -lGLEW -framework OpenGL -std=c++11

run:
	make compile
	./a.out